### ISSUE TITLE
Map coordinates interpreted inconsistently

### ISSUE THREAD

**Issue by leighgarbs** [leighgarbs/cs420-game#15]
Ship movement isn't working because there's some confusion on the map coordinate system.  The Map class internally represents the map in (row, column) format, and the call to getTerrain interprets its arguments as (row, column).  The game logic interfaces with the map using getTerrain, and expects the getTerrain arguments to be (x, y), where

top-left  --------------------------------> positive X this way
 |
 |
 |
 |
 |
\/
positive Y this way

What do we want here?  I think the game logic interpretation makes a bit more sense but I haven't really been involved in the map development, so I don't know.

**Comment by leighgarbs** [comment]
A related question: what do the parameters in the ShipMoveCmdEvent vector mean?  Is it an X, Y pair where a 1 for X means

-------------------> move this way

a -1 for X means

move this way <------------------------

a 1 for Y means

 |
 |
 |
 |
\/
move this way

and a -1 for Y means

move this way
/\
 |
 |
 |
 |

**Comment by jpszabo** [comment]
I think the x,y system is much better than the row,col system. I wasn't
thinking of that inconsistency when I originally implemented the map but
it's pretty obvious now when we're putting everything together.
