### ISSUE TITLE
Game logic needs to pause when player is in a menu

### ISSUE THREAD

**Issue by leighgarbs** [leighgarbs/cs420-game#16]
This is probably best accomplished by having the main loop set the game time factor to 0 when a transaction is happening.  Can add event handlers in rum_runners.cpp that do this on TransactionStartEvent and TransactionSuccess/FailEvent.

**Comment by lifesurfeit** [comment]
If the event handlers are in rum_runners.cpp, how do we access the event types of the events stored in GameLogic's event_manager? Also, once game_logic.update occurs, won't the transaction have started and ended already?

**Comment by leighgarbs** [comment]
We'll probably need stand-alone C-style functions to serve as the event handlers in rum_runners.cpp for this.  The code will need to register those event handlers with the transaction events in the game logic's event manager before the game enters the main loop.  The game time factor will probably also need to be moved out of the main() function and up into file scope (defined up with the #defines at the top of the file) so the event handlers can see it.

Right now transactions take no time because we haven't implemented them fully.  Eventually transactions will take some time (from the perspective of the game) because the user will be inputting numbers into a menu during the transaction.  Right now the game handles the transaction entirely so it's real quick.  Even so, it's still going to take more than a frame to complete a transaction, since the game logic needs input from the game view (in the form of the TransactionCheckEvent) before the transaction can complete.  That won't happen until the game view updates after the game logic starts the transaction.

**Comment by lifesurfeit** [comment]
Sorry about the delay in fixing this. Just pushed to branch gamepause.

**Comment by lifesurfeit** [comment]
Having some trouble binding event delegates to the event_manager. Could you take a look?
