### ISSUE TITLE
Actors and their storage in GameLogic needs to be updated

### ISSUE THREAD

**Issue by leighgarbs** [leighgarbs/cs420-game#17]
Actors aren't properly stored in any kind of data structure in the game logic.  They also aren't updated.  An accessor to the actor list needs to be added so the game views can obtain actor data.

**Comment by leighgarbs** [comment]
I should have this fixed on a branch tonight sometime.

**Comment by jpszabo** [comment]
If you get a chance to merge the consistent_map_coordinates and
map_with_sprites branches with master (provided everyone is on board with
those changes), I can put up a branch tonight of adding the draw functions
to the HumanGameView.
