### ISSUE TITLE
Game view does not have enough information available to be able to draw actors appropriately

### ISSUE THREAD

**Issue by leighgarbs** [leighgarbs/cs420-game#18]
To fix this we decided to implement a singleton database class which stores an ActorId -> "actor type" (yet to be defined) mapping.  This way code (primarily the game view at the moment) can query this database with an ActorId and obtain the information necessary to draw the actor.

**Comment by leighgarbs** [comment]
Actually, what if we just put an enumeration field in the Actor class itself that specifies that actor's type?  That'd be easier than storing the data external to Actor in a database, each actor would just know it's own type.  So each actor would have an "ActorType" field defined like so ...

``` c++
enum ActorType
{
  SHIP,
  BUY_PORT,
  SELL_PORT
};
```

... and we'd add to this list of potential types as we define more actor types.

**Comment by leighgarbs** [comment]
Justin, we probably don't need to do this ActorType enum thing anymore, do we?  The game logic has an accessor for just the ports, and you can tell if a port is a buy or sell port with the isBuyPort(), so that's probably good enough for now, right?

**Comment by mrfievel** [comment]
Yeah I agree an enum would be a lot simpler
