### ISSUE TITLE
Map doesn't support window resizing

### ISSUE THREAD

**Issue by leighgarbs** [leighgarbs/cs420-game#31]
Currently supports only 800x600 resolution

**Comment by leighgarbs** [comment]
The new code from the map_window_data branch that just went to master should help out with this.  The Map stores a tile size, but it really shouldn't, that should be in the game view since the game view is drawing the map.  All the existing references to the Map's tile size should be changed to the one in HumanGameView.

**Comment by jpszabo** [comment]
So I've added a scale factor to the drawing of both the map and the actors
and it works pretty well. Want me to add a branch?

**Comment by jpszabo** [comment]
It doesn't center the map yet, it just scales all of the sprites
appropriately.
