### ISSUE TITLE
Map "block-y ness"

### ISSUE THREAD

**Issue by jpszabo** [leighgarbs/cs420-game#50]
So I think I can probably tackle this before Tuesday. This would be ideal because Professor Peers brought it up as something we should fix for this presentation. 

Attached there is a screenshot from what I have now. If you guys like it, I'll fix up the whole map to use these kinds of sprites. I've redone the upper left land mass, so the rest of the map would look similar.

Ports will probably have to be moved and they won't fit quite as snug as they used to but I can handle moving the ports, and you'll have to decide for yourself how it looks. Let me know!

![screen shot 2014-11-09 at 4 38 47 pm](https://cloud.githubusercontent.com/assets/6267827/4969112/d1ccb9ce-6858-11e4-9858-6d827fa0aa6b.png)

**Comment by jpszabo** [comment]
I edited the map file to be a CSV with integer values. This allows greater flexibility in specifying what sprite tile to place there. Our previous way of using an ENUM for Land and Water seemed a bit unnecessary; instead of creating a map of L's and W's we could have simply created a map with 0's and 1's so that has been removed. Plain water (navigable by the ship) still takes the value of 0 inside the map_array, while various land arrangements take on integer values greater than 0 (not navigable by the ship). The integer value that each land arrangement takes on directly corresponds to its position in the sprite sheet. The first sprite starts at (0,200) and each one is laid out in succession (25,200), (50,200), etc. which makes the drawing of the map more concise as well. I'll push my branch as it is now so that you can see what I'm doing, and maybe some of this will make sense.

**Comment by lifesurfeit** [comment]
Looks awesome!

**Comment by mrfievel** [comment]
That looks really good!

**Comment by jpszabo** [comment]
My only concern is that it makes things (the ship, and the writing over the
ports) more difficult to see because of all the white in the water.

**Comment by jpszabo** [comment]
I've finalized the map. The screen shot is below. As you can see, I had to move some ports around so some of them are more difficult to get to, which I think will add to the complexity/fun of the game if we can balance out the ship speed and the rates of each port. Do you think it would be possible to merge this into Master before our presentation tomorrow? I would say our options are either 1.) I demo the game as is tomorrow and just show this screen shot of the map or 2.) Merge the map into master and during the demo I can talk about how things need to be balanced more.

 I'm going to push the branch again now. I had to change the port file to move some of the ports around and I had to move the starting position of the ship because it was starting on land, so that's why GameLogic has been edited. 

Let me know what you think!
![screen shot 2014-11-10 at 2 48 03 pm](https://cloud.githubusercontent.com/assets/6267827/4982468/f5981546-6912-11e4-9da2-9875556408af.png)

**Comment by jpszabo** [comment]
Also, by "finalized the map" I mean I think it looks good, but I am very open to suggestions for changes that could be made. I will start working on the presentation soon.

**Comment by leighgarbs** [comment]
Are the beach tiles classified as land?  If they were classified water the ports could be moved onto the beach, which might make them look less they're sitting out in the ocean.

**Comment by jpszabo** [comment]
Right now, no but I think that is an easy fix.

I'm trying to merge master into my branch but there are some conflicts. One
of them involves the sprite file. Do you have any idea how to resolve that?
Is there a way to force my file to be the file that gets used and disregard
the other version?

**Comment by jpszabo** [comment]
So with the way things are implemented, putting the ports onto the beach doesn't look that great (see below). If the positions of ports could be floats that might work.

![screen shot 2014-11-10 at 3 37 08 pm](https://cloud.githubusercontent.com/assets/6267827/4983333/c6ffc722-6919-11e4-97b1-8ce20ef87740.png)

**Comment by leighgarbs** [comment]
I'm not familiar with how git deals with conflicts with binary files.  With text files a conflict is marked resolved when you run 'git add' on it after the merge, so maybe you just have to make sure the sprite file you want is there then run 'git add' on it?

It's odd that the sprite file is in conflict.  Did you create this branch yesterday before your map_resizing branch went to master?  That would explain it.  (EDIT: Or would it?  Don't listen to me)

About the port placement, yeah, I guess that doesn't look as good as it did in my mind.  Maybe if they were drawn bigger than one tile in size (1.5x maybe)?  Regardless I think this will show better than our old map and is worth having.

**Comment by jpszabo** [comment]
The 1.5x port sizing is a good idea. On first attempt, it looks decent but would need some tweaking. I think I'll leave them the way they are for now, but that will be something to do in the future (or quickly before tomorrow's presentation if I have time). 

I also like the idea of the ship being able to move on the beaches, because that looks a little better when you're actually playing it, so I'll include that change in the branch too unless anyone objects.
