### ISSUE TITLE
Sound?

### ISSUE THREAD

**Issue by leighgarbs** [leighgarbs/cs420-game#53]
Do we want sound for our game?  Maybe we can start putting some thoughts down here if so.

Contain within new Sound class stored in HumanGameView
- listens for events in game logic
- plays sounds when certain events occur

**Comment by leighgarbs** [comment]
Time to start referencing your favorite pirate-themed games.  Skies of Arcadia!
https://www.youtube.com/watch?v=9J6NdIpC2QE

**Comment by lifesurfeit** [comment]
I'm currently in a computer music class so I can try to whip something up!

**Comment by mrfievel** [comment]
That'd be awesome, think you could make something piratey?

**Comment by lifesurfeit** [comment]
I'll definitely try. I can get a sample up soon.

**Comment by lifesurfeit** [comment]
Sorry I haven't pushed anything recently, I have an interview today but should be able to put something up tomorrow.

**Comment by leighgarbs** [comment]
Christine how's this coming?  Anything you want us to try?

**Comment by lifesurfeit** [comment]
I'm still working on reworking the Sound class but it should be up soon.

**Comment by lifesurfeit** [comment]
Sound works now! I wasn't able to listen in lab as I forgot my headphones but please pull and let me know how it sounds.

**Comment by lifesurfeit** [comment]
Will probably add music for opening screen and ending screens later tonight.
