### ISSUE TITLE
Implement win/lose conditions

### ISSUE THREAD

**Issue by leighgarbs** [leighgarbs/cs420-game#56]
Lose conditions
- Player reaches 0 rum 0 gold
- Player runs out of time

Win conditions
- Player moves to loan shark port with enough gold

Display title screen, win and lose screens when appropriate

GameStartEvent, GameWinEvent, GameLoseEvent

**Comment by leighgarbs** [comment]
How should the "loan shark port" be determined?
- Choose a random port on game start?
- Always one set port (defined in ports.txt)?

We'll probably want to draw the loan shark port differently.  Maybe put a loan shark icon in the UI.

**Comment by mrfievel** [comment]
Maybe a uniquely named port like shark bait island or something?

**Comment by lifesurfeit** [comment]
I think that sounds good!

**Comment by jpszabo** [comment]
Hey all,

I just put up my initial attempt to tackle the win/lose condition stuff. Right now, when rum and gold both go to zero a message pops up in the dialog box to say that you've lost, and gives you the option to press [return] to play again. Right now I'm trying to implement a "GameStartEvent" and I'm thinking what should happen is the GameLogic should just reset itself, but I'm not exactly sure how to go about that. Does anyone have any suggestions as to how to do this, or a different way of doing things?

I also need to pause the game when the "You lose" message pops up. I know the code to do that is in there somewhere, but I'll get to that later.

**Comment by leighgarbs** [comment]
You'll definitely want to merge from master.  The Ship and Port update functions changed a lot when integer_rum_gold merged.  The code to update the rum amount is sadly a lot more than a single multiplication now, and since we want the gold to update in basically the same way, just twice the rate, we'll probably want to use that same code for updating the gold when rum hits zero.  It might be best to put the rum update code in a function and then use that function to update both the rum and gold, that way we don't have duplicate code.

Is there a reason for the GameEndEvent?  Could the game logic just go straight to tossing a GameWonEvent or GameLostEvent when appropriate?

The best way to track game state is likely with an enumeration, where the states are something like IN_PROGRESS, WON, LOST, or STARTING.

I think what we decided we want is for the game logic to re-initialize itself when the GameStartEvent is triggered.  I think that means we want a call to GameLogic::initialize to do this, so it would need to be callable at any time.  Right now that's not the case, so most of the work on that task would be rearranging code so that is the case.  It may also be necessary to re-initialize all the game views when the game starts over.

**Comment by leighgarbs** [comment]
Anyone else have anything?  Do we want to use the dialog box for game win and lose or go for something else, like a picture?

**Comment by jpszabo** [comment]
It can just be a GameLoseEvent and GameWonEvent, I'll change that.

I was thinking the game views would just reset on their update after the
gamelogic was reinitialized but you might be right.

I'm not going to be able to get to any of this until late Thursday and I
had an interview pop up on Friday that I wasn't expecting so I think I'm
going to need some help on this.

**Comment by lifesurfeit** [comment]
I can take a look at this tomorrow.

**Comment by jpszabo** [comment]
I just put up a new branch for the win/lose stuff, which is now merged with master. So far I have a lose event when rum and gold both = 0, and a restart event when spacebar is pressed. A "YOU LOSE" textfield pops up when you lose, and it is supposed to be cleared when the game restarts but for some reason it is getting reset to "YOU LOSE" after it has been cleared. I'm going to hunt around for it but if someone else can take a look, I'd really appreciate it.

Right now when the game restarts I don't do anything with the ports. My initial thought was to copy the code from the constructor into the resetStartValues() method but something tells me there's a better way to do it.

**Comment by jpszabo** [comment]
As indicated in my commit comments, I implemented a game timer which causes the player to lose after 5 minutes. It is displayed in the center-right top portion of the screen as "time remaining." It displays one second fewer than the player actually has, but it doesn't look too bad when it hangs at 0:00 for one second before the "YOU LOSE" message pops up.

I also fixed a mistake I made when I forgot to reset the gold rate to be 0 after the player buys more rum. I'll work on the winning condition events tomorrow. That should be done hopefully by noon. After that I'll try to hunt down the reason that the "YOU LOSE" message is being displayed after the game restarts. It might just take sending another event to HGV telling it to clear the gameState string?

Later in the afternoon I'll start working on pngs for the losing, winning, and starting screens because I don't think those will be too difficult to implement.

**Comment by jpszabo** [comment]
So to try to debug this, I required the setGameState method to take a string of the method that called it. This revealed that the gameLostEventHandler is called once after readInputs is called which is causing the message to revert back to "YOU LOSE". Is there any way to prevent gameLoseEventHandler from being called again? Does anyone have any insight into this? Once this issue gets resolved I can move on to bigger and better things like start screens and such...

**Comment by leighgarbs** [comment]
That should only run when GameLostEvents are queued.  Is another GameLostEvent happening for some reason?

**Comment by jpszabo** [comment]
It's actually happening many times ( I knew you would know!). Each time
game logic updates it checks the amount of rum and gold that the ship has
and queues a game lost event. how could I make it so that event just queues
once?

**Comment by leighgarbs** [comment]
Um ... only call queueEvent() once :)

**Comment by jpszabo** [comment]
Ha. Of course!
