### ISSUE TITLE
Enemies

### ISSUE THREAD

**Issue by leighgarbs** [leighgarbs/cs420-game#57]
Implement basic enemies.  Two initial behaviors, patrol and pursue
Enemy AI should be in a new AIGameView
- commands issued to AI actors in game logic via events
- enemies should have Actor as a parent or ancestor

**Comment by jpszabo** [comment]
http://www.spriters-resource.com/genesis_32x_scd/sf2/sheet/24249/

**Comment by leighgarbs** [comment]
This was resolved with #72.
