### ISSUE TITLE
Game unpauses after a transaction fail

### ISSUE THREAD

**Issue by jpszabo** [leighgarbs/cs420-game#61]
If you attempt a transaction and fail, the game unpauses itself.

**Comment by lifesurfeit** [comment]
I think it's supposed to do that. You have to retry the transaction again
later.

**Comment by leighgarbs** [comment]
Yeah this is a bug.  When a transaction fails the window stays open, but the game unpauses.  I think all that needs to happen here is we don't run the "unpause" event handler on transaction fail.  Right now it runs for both transaction success and fail.

**Comment by lifesurfeit** [comment]
Ok, so I should have separate handlers for each? I had two earlier but
merged into one handler on your suggestion.

**Comment by leighgarbs** [comment]
No we don't need separate handlers, we just need the unpause handler to not run when the transaction fail event happens.  Just need to remove the code that registers the unpause handler with transaction fail.

**Comment by lifesurfeit** [comment]
Pull request #64
