### ISSUE TITLE
Start-up screen

### ISSUE THREAD

**Issue by jpszabo** [leighgarbs/cs420-game#70]
So everyone has something to do right now, and this isn't essential but if there's anytime leftover this would really make our game look good. 

I think in its simplest form, the game starts out paused and a dialog window (using Justin's UI window stuff) pops up and explains the game/situation. The user can then press space or enter to get rid of the window which will unpause or start the game.

**Comment by jpszabo** [comment]
Aside from the watermark which I'll get rid of, what do you guys think of this as our startup screen? I tried to match the font that I think you're using Justin. I can always change that if needed.
![screen shot 2014-11-21 at 5 41 15 pm](https://cloud.githubusercontent.com/assets/6267827/5150936/c150956a-71a5-11e4-911f-8ca4597d35ef.png)

**Comment by jpszabo** [comment]
Here it is, no watermark.
![title_screen](https://cloud.githubusercontent.com/assets/6267827/5151048/15964c22-71a7-11e4-8f9b-bd796e0cb831.png)

**Comment by mrfievel** [comment]
I like it, fits perfectly with the game.  Good job!
