### ISSUE TITLE
To win the ship should be required to go to a specific port

### ISSUE THREAD

**Issue by leighgarbs** [leighgarbs/cs420-game#81]
I forget where we left this.  Do we want to have the port the user has to get to chosen randomly when the game starts?  A special island?  I think we decided we wanted the port to get drawn differently when the ship has enough gold and should start heading for it.

**Comment by jpszabo** [comment]
My thinking was the end goal would be to have a randomly assigned port
change color (and have all the others turn to a different one maybe?) when
the player has enough gold. What I'll probably end up doing is implement it
in stages, first pick a default port that the ship has to land on to win,
then make it change color, then have it be randomly assigned. What do you
guys think of that?

**Comment by leighgarbs** [comment]
The way I can see to do this is to add another data member to the port class that indicates that that's a port the player has to go to to win.  Then check against that in game logic, same place as the current game win check is done.

A higher priority than this is probably getting the game resetting.  Jim you're still working that?  I might be able to help while doing the demo movie, but I wouldn't count on it.

**Comment by leighgarbs** [comment]
I think I like only the target port changing color, but that's just me.  Something super visible.

**Comment by jpszabo** [comment]
Okay, I can start on game resetting first. I'll start on that tomorrow, I'm
still away and I probably won't get to it tonight.

**Comment by leighgarbs** [comment]
No worries, I've been in airports all day myself ...

**Comment by leighgarbs** [comment]
Obsolete ...
