### ISSUE TITLE
THE KRAKEN

### ISSUE THREAD

**Issue by leighgarbs** [leighgarbs/cs420-game#82]
Justin, I think you're already working on this so here's an issue for it.  Implement the kraken as another enemy, distinct from the current enemies.  I think Justin already has ideas on how this should work but we can collect any additional ideas we have on this here.

**Comment by jpszabo** [comment]
I know I still need to put the kraken sprite in the sprite sheet.

**Comment by mrfievel** [comment]
Yeah, I already put states in the default enemy class that should make it pretty easy to implement, it's basically going to be 5 enemies, the head and 4 tentacles.  The head will slowly patrol while the tentacles follow the head with some offset.  I'm also going to make a merchant who's basically bonus rum that flees from you and that will be feature complete on the enemies I think with the update I pushed, let me know if we need other stuff for them.

**Comment by jpszabo** [comment]
Is this the kind of look you're going for? 
http://th04.deviantart.net/fs71/PRE/i/2013/363/8/0/day_of_the_tentacle_by_trueform-d6zxdd9.png

**Comment by mrfievel** [comment]
Yep, and that's what the enemy update branch looks like more or less once
the sprites get put in.

**Comment by jpszabo** [comment]
Cool. I'll look for something similar that we can use.

**Comment by mrfievel** [comment]
I thought we were using those ones we found last time from shining force?
Just need the head and the best looking single tentacle.

**Comment by jpszabo** [comment]
Perfect, I'm just cropping out the pink background. I'll post a branch with the new sprite sheet soon.
