### ISSUE TITLE
Time remaining indicator doesn't position itself properly at all window sizes

### ISSUE THREAD

**Issue by leighgarbs** [leighgarbs/cs420-game#85]
Sometimes it's off the screen, sometimes it's half off the screen, sometimes it's visible.

**Comment by jpszabo** [comment]
Just in case you haven't already figured this out yourself, I created a new class called UIGameTime which holds this stuff.

**Comment by jpszabo** [comment]
I think this is fixed, but now when the number of seconds is below 10, it displays as 4:9 instead of 4:09.

**Comment by mrfievel** [comment]
I just pushed a branch that fixes the seconds displaying wrong.

**Comment by leighgarbs** [comment]
If you make the window real small the time display will overlap the "Time Until Loan Shark" string.  It's a minor problem, and we won't have time to address it before we have to tag the code today anyway.

**Comment by leighgarbs** [comment]
Obsolete ...
