### ISSUE TITLE
Warnings from new enemies

### ISSUE THREAD

**Issue by jpszabo** [leighgarbs/cs420-game#93]
I get these compile warnings with master now:
/Users/localszabo/Documents/CS420/10-26-14-master/cs420-game/code/src/KrakenHead.cpp:18:1: warning: 
      control reaches end of non-void function [-Wreturn-type]
}
^
1 warning generated.
[ 24%] Building CXX object CMakeFiles/rum_runners.dir/src/KrakenTentacle.cpp.o
/Users/localszabo/Documents/CS420/10-26-14-master/cs420-game/code/src/KrakenTentacle.cpp:18:1: warning: 
      control reaches end of non-void function [-Wreturn-type]
}
^
1 warning generated.
[ 27%] Building CXX object CMakeFiles/rum_runners.dir/src/Merchant.cpp.o
/Users/localszabo/Documents/CS420/10-26-14-master/cs420-game/code/src/Merchant.cpp:19:1: warning: 
      control reaches end of non-void function [-Wreturn-type]
}
^
1 warning generated.

**Comment by jpszabo** [comment]
This might be a separate issue, but the new enemies also can go through one another (they don't collide). I think this just applies to the Kraken and merchant ship, not the pirate ships.

**Comment by mrfievel** [comment]
I tried to get it so they'd avoid each other but I never got it going in a way that didn't make things worst.  Pretty much everything can go through everything else except the tentacles won't go through the head.
