### ISSUE TITLE
UI doesn't display the amount of gold to win anywhere.

### ISSUE THREAD

**Issue by mrfievel** [leighgarbs/cs420-game#97]
There's currently no way of knowing how much gold it takes to win the game, that should definitely be somewhere.

**Comment by leighgarbs** [comment]
It does say you need 500 gold to win in one of the screens on startup.

**Comment by jpszabo** [comment]
It's in the instructions screen that I made, which you can't access after
the game starts but it's there once.

**Comment by mrfievel** [comment]
Oh OK didn't notice that.  It would still be nice to have on normal ui but
I think we've run out of time for that.

**Comment by lifesurfeit** [comment]
Maybe we can make the corner UI with gold say "X/500" and have it be red
until you reach the goal so it's more clear. I think that would be pretty
easy to do.
